apiVersion: batch/v1
kind: CronJob
metadata:
  name: dice
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          -  image: kodekloud/throw-dice
             name: throw-dice
          restartPolicy: Never
      backoffLimit: 25
      activeDeadlineSeconds: 20